### ISSUE TITLE
orbit and wsapi are not automatically installed as dependencies

### ISSUE THREAD

**Issue by cbd** [norman/lua-haml#1]
i just did a clean install of lua-haml via luarocks 2.0.1. 

luarocks doesn't detect that i didn't have orbit and wsapi... 

workaround: luarocks install orbit && luarocks install wsapi

not sure if you want to make these dependencies, and it wasn't hard to figure out, but i thought i'd put this in as a note.

**Comment by norman** [comment]
Well, that's because Lua Haml **doesn't** depend on Orbit or WSAPI. It's just like Ruby's Haml which can be used with whatever you want, and doesn't install Rails or Sinatra for you.

**Comment by cbd** [comment]
ok i see. its just the hello.lua that requires orbit... sorry about that...
