### ISSUE TITLE
luahaml command help is a little misleading

### ISSUE THREAD

**Issue by stevedonovan** [norman/lua-haml#2]
It says "luahaml -l -i '%p' " to show the expansion of the markup '%p', but this doesn't work. The -l flag is unneededd and just using -i works fine.

Also on my machine just invoking luahaml leads to a crash in haml.ext, 32, 'Haml error' after the help; it should probably just revert to the meaning of '-h'

**Comment by norman** [comment]
Both fixed. Thanks for the report!

**Comment by norman** [comment]
Improve CLI behavior - closed by 62a613bf907ef60aa9b6e195a5f12eb0eef162fe
