### ISSUE TITLE
Tabs cause render_file to never return

### ISSUE THREAD

**Issue by randrews** [norman/lua-haml#4]
When given a malformed Haml file (one that mixes spaces and tabs for indentation), render_file doesn't return. I'm cool with it raising an error or returning null (pcall would work for those cases) but never returning is probably bad...

**Comment by norman** [comment]
Ugh, definitely bad. I'll take a look into it as soon as I can.

**Comment by randrews** [comment]
I'm tracing through it right now, if I can I'll submit a patch. It's a fun problem for a Friday afternoon. :)

**Comment by norman** [comment]
If you can, I'd be grateful! I haven't had time to hack on it in a while and
know I won't get to it today.

**Comment by randrews** [comment]
Looks like one way to fix it is to remove \t from the specification for leading_whitespace at parser.lua:27. It's definitely failing after parsing it though because parser.tokenize returns something, so I'm seeing if I can find a lower-down way to fix it (that hopefully won't break tab-indented docs like this does)
