### ISSUE TITLE
Extra close tags when there are lines of whitespace

### ISSUE THREAD

**Issue by randrews** [norman/lua-haml#6]
Okay, this is just weird. Found it totally on accident. If you have lines that consist solely of whitespace, then extra close tags get inserted into the markup:

```
%html
  %body
    %table
      %tr
        %td
          Foo

      %tr
        %td
          Bar
```

renders as

```

<html> 
  <body> 
    <table> 
      <tr> 
        <td> 
          Foo
        </td> 
        <tr> 
          <td> 
            Bar
          </td> 
        </tr> 
      </tr> 
    </table> 
  </body> 
</html>
```

Note the extra /tr tag. There are 8 spaces on the line after "Foo", although it looks like Github is eating them. When you remove the 8 spaces, it renders correctly as

```

<html> 
  <body> 
    <table> 
      <tr> 
        <td> 
          Foo
        </td> 
      </tr> 
      <tr> 
        <td> 
          Bar
        </td> 
      </tr> 
    </table> 
  </body> 
</html>
```

**Comment by randrews** [comment]
Actually, looking at it more closely, it's not inserting an extra close tag as much an rearranging the tree: it took the thing after the whitespace line and made it a child of the thing before the whitespace line, even though it should be a sibling.

**Comment by norman** [comment]
I just tried this against the latest from master and it appears it was resolved at some point. Sorry the issue was ignored for so long.
