### ISSUE TITLE
if/else causes unclosed tags

### ISSUE THREAD

**Issue by wezm** [norman/lua-haml#7]
The template:

``` haml
%h1 Bug

#bug
  - for i = 1, 3 do
    %div
      - if i < 3 then
        %span
          = i
      - else
        three
```

Produces the following broken HTML:

``` html
<h1>Bug</h1>
<div id='bug'>
  <div>
    <span>
      1
  </div>
  <div>
    <span>
      2
  </div>
  <div>
      three
    </span>
  </div>
</div>
```

Instead of the expected:

``` html
<h1>Bug</h1>
<div id='bug'>
  <div>
    <span>
      1
    </span>
  </div>
  <div>
    <span>
      2
    </span>
  </div>
  <div>
    three
  </div>
</div>
```

The workaround I'm using is to not use else, but instead an inverted version of the original if.

**Comment by norman** [comment]
Thanks for the report, will take a look into this soon.

**Comment by norman** [comment]
This is actually already fixed in master, but hasn't been released to Luarocks yet. I'll release a new rock version ASAP and close this issue once that's been done.

**Comment by wezm** [comment]
Great, thanks.

**Comment by norman** [comment]
Sorry for the delay on this. A new version of LuaHaml has now been released to Luarocks with this fix.
